program leMondeDeKelloWoutAlan;


{$APPTYPE CONSOLE}

{$R *.res}


uses
  SysUtils,
  MMSystem,
  attaqueSortAdv in 'Liste des unitées\Combat\Attaque\Gestion\attaqueSortAdv.pas',
  adversaireAttaque in 'Liste des unitées\Combat\Attaque\Gestion\adversaireAttaque.pas',
  formulePvRestant in 'Liste des unitées\Combat\Formules\Autre\formulePvRestant.pas',
  combatFin in 'Liste des unitées\Combat\Interface\combatFin.pas',
  actualisationEcranCombat in 'Liste des unitées\Combat\Interface\actualisationEcranCombat.pas',
  formuleOr in 'Liste des unitées\Combat\Formules\Autre\formuleOr.pas',
  formuleXp in 'Liste des unitées\Combat\Formules\Autre\formuleXp.pas',
  monterNiv in 'Liste des unitées\Gestion de niveaux\monterNiv.pas',
  formuleDegatSort in 'Liste des unitées\Combat\Formules\Autre\formuleDegatSort.pas',
  adversaireAttaqueHybride in 'Liste des unitées\Combat\Attaque\Selon classe\adversaireAttaqueHybride.pas',
  adversaireAttaqueGuerrier in 'Liste des unitées\Combat\Attaque\Selon classe\adversaireAttaqueGuerrier.pas',
  adversaireAttaqueRodeur in 'Liste des unitées\Combat\Attaque\Selon classe\adversaireAttaqueRodeur.pas',
  adversaireAttaqueVampire in 'Liste des unitées\Combat\Attaque\Selon classe\adversaireAttaqueVampire.pas',
  adversaireAttaqueMage in 'Liste des unitées\Combat\Attaque\Selon classe\adversaireAttaqueMage.pas',
  formuleDegat in 'Liste des unitées\Combat\Formules\Autre\formuleDegat.pas',
  effAdv in 'Liste des unitées\Combat\Variables\effAdv.pas',
  barrePv in 'Liste des unitées\Combat\Interface\barrePv.pas',
  classeTitre in 'Liste des unitées\Creation de personnage\Classe\classeTitre.pas',
  classe in 'Liste des unitées\Creation de personnage\Classe\classe.pas',
  initialisationDesStats in 'Liste des unitées\Creation de personnage\Classe\initialisationDesStats.pas',
  map in 'Liste des unitées\Map\map.pas',
  formulePv in 'Liste des unitées\Combat\Formules\Stats\formulePv.pas',
  formuleAttaque in 'Liste des unitées\Combat\Formules\Stats\formuleAttaque.pas',
  formuleDefense in 'Liste des unitées\Combat\Formules\Stats\formuleDefense.pas',
  formuleVitesse in 'Liste des unitées\Combat\Formules\Stats\formuleVitesse.pas',
  defineValsPers in 'Liste des unitées\Combat\Variables\defineValsPers.pas',
  entrerNom in 'Liste des unitées\Creation de personnage\Nom\entrerNom.pas',
  choisirSonAspect in 'Liste des unitées\Creation de personnage\Nom\choisirSonAspect.pas',
  genererNomAleatoire in 'Liste des unitées\Creation de personnage\Nom\genererNomAleatoire.pas',
  genererNombreAleatoire in 'Liste des unitées\Gestion des variables\genererNombreAleatoire.pas',
  verificationNom in 'Liste des unitées\Creation de personnage\Nom\verificationNom.pas',
  imageProf in 'Liste des unitées\Creation de personnage\Interface\imageProf.pas',
  questionImage in 'Liste des unitées\Gestion des interfaces\questionImage.pas',
  tableXp in 'Liste des unitées\Gestion de niveaux\tableXp.pas',
  insererLignes in 'Liste des unitées\Gestion des interfaces\insererLignes.pas',
  histoire in 'Liste des unitées\Menu\histoire.pas',
  credit in 'Liste des unitées\Menu\credit.pas',
  GestionEcran in 'Liste des unitées\Gestion des interfaces\GestionEcran.pas',
  sortBouleDeFeu in 'Liste des unitées\Combat\Attaque\Sorts\sortBouleDeFeu.pas',
  ram in 'Liste des unitées\Gestion des variables\ram.pas',
  attaqueSortPers in 'Liste des unitées\Combat\Attaque\Gestion\attaqueSortPers.pas',
  sortGlaciation in 'Liste des unitées\Combat\Attaque\Sorts\sortGlaciation.pas',
  peche in 'Liste des unitées\Compétences\peche.pas',
  coupe in 'Liste des unitées\Compétences\coupe.pas',
  actualisationDecranMinage in 'Liste des unitées\Compétences\Interface\actualisationDecranMinage.pas',
  minage in 'Liste des unitées\Compétences\minage.pas',
  minageText in 'Liste des unitées\Compétences\data\minageText.pas',
  verificationCoordonneesMap in 'Liste des unitées\Map\verificationCoordonneesMap.pas',
  combat in 'Liste des unitées\Combat\combat.pas',
  effPers in 'Liste des unitées\Combat\Variables\effPers.pas',
  joueurAttaque in 'Liste des unitées\Combat\Attaque\Gestion\joueurAttaque.pas',
  joueurAttaqueGuerrier in 'Liste des unitées\Combat\Attaque\Selon classe\joueurAttaqueGuerrier.pas',
  joueurAttaqueRodeur in 'Liste des unitées\Combat\Attaque\Selon classe\joueurAttaqueRodeur.pas',
  joueurAttaqueMage in 'Liste des unitées\Combat\Attaque\Selon classe\joueurAttaqueMage.pas',
  joueurAttaqueVampire in 'Liste des unitées\Combat\Attaque\Selon classe\joueurAttaqueVampire.pas',
  combatFuire in 'Liste des unitées\Combat\combatFuire.pas',
  joueurChoisirSortAttaque in 'Liste des unitées\Combat\Interface\joueurChoisirSortAttaque.pas',
  formuleFuire in 'Liste des unitées\Combat\Formules\Autre\formuleFuire.pas',
  codesCommande in 'Liste des unitées\Map\codesCommande.pas',
  sauvegarder in 'Liste des unitées\Sauvegardement\sauvegarder.pas',
  dataMouvement in 'Liste des unitées\Map\Commandes\dataMouvement.pas',
  dataTriche in 'Liste des unitées\Map\Commandes\dataTriche.pas',
  chargement in 'Liste des unitées\Sauvegardement\chargement.pas',
  jeu in 'Liste des unitées\Menu\jeu.pas',
  menuInterface in 'Liste des unitées\Menu\menuInterface.pas',
  ecranTitre in 'Liste des unitées\Menu\ecranTitre.pas',
  imageET1 in 'Liste des unitées\Menu\Images Ecran Titre\imageET1.pas',
  imageET7 in 'Liste des unitées\Menu\Images Ecran Titre\imageET7.pas',
  imageET8 in 'Liste des unitées\Menu\Images Ecran Titre\imageET8.pas',
  imageET9 in 'Liste des unitées\Menu\Images Ecran Titre\imageET9.pas',
  imageET10 in 'Liste des unitées\Menu\Images Ecran Titre\imageET10.pas',
  imageET11 in 'Liste des unitées\Menu\Images Ecran Titre\imageET11.pas',
  imageET12 in 'Liste des unitées\Menu\Images Ecran Titre\imageET12.pas',
  imageET13 in 'Liste des unitées\Menu\Images Ecran Titre\imageET13.pas',
  imageET14 in 'Liste des unitées\Menu\Images Ecran Titre\imageET14.pas',
  imageET15 in 'Liste des unitées\Menu\Images Ecran Titre\imageET15.pas',
  imageET16 in 'Liste des unitées\Menu\Images Ecran Titre\imageET16.pas',
  imageET17 in 'Liste des unitées\Menu\Images Ecran Titre\imageET17.pas',
  imageET18 in 'Liste des unitées\Menu\Images Ecran Titre\imageET18.pas',
  imageET19 in 'Liste des unitées\Menu\Images Ecran Titre\imageET19.pas',
  imageET20 in 'Liste des unitées\Menu\Images Ecran Titre\imageET20.pas',
  imageET21 in 'Liste des unitées\Menu\Images Ecran Titre\imageET21.pas',
  imageET22 in 'Liste des unitées\Menu\Images Ecran Titre\imageET22.pas',
  imageET23 in 'Liste des unitées\Menu\Images Ecran Titre\imageET23.pas',
  imageET24 in 'Liste des unitées\Menu\Images Ecran Titre\imageET24.pas',
  imageET25 in 'Liste des unitées\Menu\Images Ecran Titre\imageET25.pas',
  imageET26 in 'Liste des unitées\Menu\Images Ecran Titre\imageET26.pas',
  imageET27 in 'Liste des unitées\Menu\Images Ecran Titre\imageET27.pas',
  imageET28 in 'Liste des unitées\Menu\Images Ecran Titre\imageET28.pas',
  imageET29 in 'Liste des unitées\Menu\Images Ecran Titre\imageET29.pas',
  imageET2 in 'Liste des unitées\Menu\Images Ecran Titre\imageET2.pas',
  imageET3 in 'Liste des unitées\Menu\Images Ecran Titre\imageET3.pas',
  imageET4 in 'Liste des unitées\Menu\Images Ecran Titre\imageET4.pas',
  imageET5 in 'Liste des unitées\Menu\Images Ecran Titre\imageET5.pas',
  imageET6 in 'Liste des unitées\Menu\Images Ecran Titre\imageET6.pas',
  imageET30 in 'Liste des unitées\Menu\Images Ecran Titre\imageET30.pas',
  imageET31 in 'Liste des unitées\Menu\Images Ecran Titre\imageET31.pas',
  imageET32 in 'Liste des unitées\Menu\Images Ecran Titre\imageET32.pas',
  menu in 'Liste des unitées\Menu\menu.pas',
  creationPersonnage in 'Liste des unitées\Creation de personnage\creationPersonnage.pas',
  confirmation in 'Liste des unitées\Menu\confirmation.pas',
  entrerSexe in 'Liste des unitées\Creation de personnage\Sexe\entrerSexe.pas',
  defineValsAdv in 'Liste des unitées\Combat\Variables\defineValsAdv.pas',
  galackData in 'Liste des unitées\Companion\galackData.pas',
  msgErreur in 'Liste des unitées\Map\msgErreur.pas',
  objetsMap in 'Liste des unitées\Map\objetsMap.pas',
  pnj in 'Liste des unitées\Map\pnj.pas',
  interfaceJeu in 'Liste des unitées\Compétences\interfaceJeu.pas',
  sac in 'Liste des unitées\Compétences\sac.pas',
  potion in 'Liste des unitées\Objets\potion.pas',
  sPotion in 'Liste des unitées\Objets\sPotion.pas',
  mPotion in 'Liste des unitées\Objets\mPotion.pas',
  livreDeCombat in 'Liste des unitées\Objets\livreDeCombat.pas',
  tribulus in 'Liste des unitées\Objets\tribulus.pas',
  propolis in 'Liste des unitées\Objets\propolis.pas',
  ginseng in 'Liste des unitées\Objets\ginseng.pas',
  omega3 in 'Liste des unitées\Objets\omega3.pas',
  aide in 'Liste des unitées\Compétences\aide.pas',
  objetErreur in 'Liste des unitées\Objets\objetErreur.pas',
  stats in 'Liste des unitées\Compétences\stats.pas',
  config in 'Liste des unitées\Compétences\config.pas',
  sortBlizzard in 'Liste des unitées\Combat\Attaque\Sorts\sortBlizzard.pas',
  sortHydroblast in 'Liste des unitées\Combat\Attaque\Sorts\sortHydroblast.pas',
  sortOndeDeChoc in 'Liste des unitées\Combat\Attaque\Sorts\sortOndeDeChoc.pas',
  sortTornade in 'Liste des unitées\Combat\Attaque\Sorts\sortTornade.pas',
  sortJetDeFeu in 'Liste des unitées\Combat\Attaque\Sorts\sortJetDeFeu.pas',
  sortSeisme in 'Liste des unitées\Combat\Attaque\Sorts\sortSeisme.pas',
  sortAeroblast in 'Liste des unitées\Combat\Attaque\Sorts\sortAeroblast.pas',
  sortFeuSacre in 'Liste des unitées\Combat\Attaque\Sorts\sortFeuSacre.pas',
  sortBouleOmbre in 'Liste des unitées\Combat\Attaque\Sorts\sortBouleOmbre.pas',
  sortCorruption in 'Liste des unitées\Combat\Attaque\Sorts\sortCorruption.pas',
  sortTenebres in 'Liste des unitées\Combat\Attaque\Sorts\sortTenebres.pas',
  sortOndeNoire in 'Liste des unitées\Combat\Attaque\Sorts\sortOndeNoire.pas',
  sortTyphonNoir in 'Liste des unitées\Combat\Attaque\Sorts\sortTyphonNoir.pas',
  sortBouleDeSang in 'Liste des unitées\Combat\Attaque\Sorts\sortBouleDeSang.pas',
  sortMalediction in 'Liste des unitées\Combat\Attaque\Sorts\sortMalediction.pas',
  sortFeuEnfer in 'Liste des unitées\Combat\Attaque\Sorts\sortFeuEnfer.pas',
  sortChuteNoire in 'Liste des unitées\Combat\Attaque\Sorts\sortChuteNoire.pas',
  sortSacrifice in 'Liste des unitées\Combat\Attaque\Sorts\sortSacrifice.pas',
  sortSoignage in 'Liste des unitées\Combat\Attaque\Sorts\sortSoignage.pas',
  sortAntiSoin in 'Liste des unitées\Combat\Attaque\Sorts\sortAntiSoin.pas',
  apprendreSortsMage in 'Liste des unitées\Map\apprendreSortsMage.pas';

var
  utiliserOutilsDev: Integer;
{Si vous mettez ce valeur à 1, des commandes divers de triche sont autorisées comme par exemple le
traversage des murs, la génération des combats, etc.}


begin
//Changez cette valeur si vous voudrez activer les commandes de triche et de débugage.
//0 = Desactivé, 1 = Activé
  utiliserOutilsDev := 0;
  ecrireIntegerRam(72, utiliserOutilsDev);

  demarEcranTitre;
end.
